[providers]
exclude = ["node"]

[phases.setup]
nixPkgs = [
    "python311",
    "cairo",
    "pango",
    "glib",
    "fontconfig"
]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"